/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "txypbmtiddzurtjxjnyb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4eXBibXRpZGR6dXJ0anhqbnliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg1MjI1OTgsImV4cCI6MjA5NDA5ODU5OH0.V7S1_om13vI-QpLk3WFTXjiPv9OZ6-_PuQ-T4fJhQcY"